/*
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStateMachineDslScopeProvider extends DelegatingScopeProvider {
}
