/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext;

import org.salgar.swf_statemachine.xtext.StateMachineDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateMachineDslStandaloneSetup extends StateMachineDslStandaloneSetupGenerated {
  public static void doSetup() {
    StateMachineDslStandaloneSetup _stateMachineDslStandaloneSetup = new StateMachineDslStandaloneSetup();
    _stateMachineDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
