/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext;

import org.salgar.swf_statemachine.xtext.AbstractStateMachineDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateMachineDslRuntimeModule extends AbstractStateMachineDslRuntimeModule {
}
