/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.scoping;

import org.salgar.swf_statemachine.xtext.scoping.AbstractStateMachineDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class StateMachineDslScopeProvider extends AbstractStateMachineDslScopeProvider {
}
