/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.stateMachineDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.salgar.swf_statemachine.xtext.stateMachineDsl.AttributeBase;
import org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachineDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Base</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AttributeBaseImpl extends MinimalEObjectImpl.Container implements AttributeBase
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeBaseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateMachineDslPackage.Literals.ATTRIBUTE_BASE;
  }

} //AttributeBaseImpl
