/*
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.salgar.swf_statemachine.xtext.parser.antlr.internal.InternalStateMachineDslParser;
import org.salgar.swf_statemachine.xtext.services.StateMachineDslGrammarAccess;

public class StateMachineDslParser extends AbstractAntlrParser {

	@Inject
	private StateMachineDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStateMachineDslParser createParser(XtextTokenStream stream) {
		return new InternalStateMachineDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public StateMachineDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StateMachineDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
