/*
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StateMachineDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/salgar/swf_statemachine/xtext/parser/antlr/internal/InternalStateMachineDsl.tokens");
	}
}
