/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.stateMachineDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Base</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachineDslPackage#getAttributeBase()
 * @model
 * @generated
 */
public interface AttributeBase extends EObject
{
} // AttributeBase
