/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.stateMachineDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Control Object Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute#getName <em>Name</em>}</li>
 *   <li>{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachineDslPackage#getControlObjectAttribute()
 * @model
 * @generated
 */
public interface ControlObjectAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachineDslPackage#getControlObjectAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(AttributeBase)
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachineDslPackage#getControlObjectAttribute_Type()
   * @model containment="true"
   * @generated
   */
  AttributeBase getType();

  /**
   * Sets the value of the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(AttributeBase value);

} // ControlObjectAttribute
