/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.stateMachineDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.PackageDeclaration#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachineDslPackage#getPackageDeclaration()
 * @model
 * @generated
 */
public interface PackageDeclaration extends Base
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Base}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachineDslPackage#getPackageDeclaration_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Base> getElements();

} // PackageDeclaration
