/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.stateMachineDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachineDslFactory
 * @model kind="package"
 * @generated
 */
public interface StateMachineDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "stateMachineDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.salgar.org/swf_statemachine/xtext/StateMachineDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "stateMachineDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StateMachineDslPackage eINSTANCE = org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ModelImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.BaseImpl <em>Base</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.BaseImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getBase()
   * @generated
   */
  int BASE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE__NAME = 0;

  /**
   * The number of structural features of the '<em>Base</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.PackageDeclarationImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getPackageDeclaration()
   * @generated
   */
  int PACKAGE_DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__NAME = BASE__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__ELEMENTS = BASE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Package Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION_FEATURE_COUNT = BASE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineImpl <em>State Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getStateMachine()
   * @generated
   */
  int STATE_MACHINE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__NAME = BASE__NAME;

  /**
   * The feature id for the '<em><b>Initial State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__INITIAL_STATE = BASE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Control Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__CONTROL_OBJECT = BASE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__EVENTS = BASE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__STATES = BASE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>State Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE_FEATURE_COUNT = BASE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getState()
   * @generated
   */
  int STATE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__TRANSITIONS = 1;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.TransitionImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TARGET = 1;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TRIGGER = 2;

  /**
   * The feature id for the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__GUARD = 3;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__ACTION = 4;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.EventImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.GuardImpl <em>Guard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.GuardImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getGuard()
   * @generated
   */
  int GUARD = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUARD__NAME = 0;

  /**
   * The number of structural features of the '<em>Guard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUARD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ActionImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ControlObjectImpl <em>Control Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ControlObjectImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getControlObject()
   * @generated
   */
  int CONTROL_OBJECT = 9;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_OBJECT__ATTRIBUTES = 0;

  /**
   * The number of structural features of the '<em>Control Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_OBJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ControlObjectAttributeImpl <em>Control Object Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ControlObjectAttributeImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getControlObjectAttribute()
   * @generated
   */
  int CONTROL_OBJECT_ATTRIBUTE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_OBJECT_ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_OBJECT_ATTRIBUTE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Control Object Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_OBJECT_ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.AttributeBaseImpl <em>Attribute Base</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.AttributeBaseImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getAttributeBase()
   * @generated
   */
  int ATTRIBUTE_BASE = 11;

  /**
   * The number of structural features of the '<em>Attribute Base</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_BASE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.SimpleTypeImpl <em>Simple Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.SimpleTypeImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getSimpleType()
   * @generated
   */
  int SIMPLE_TYPE = 12;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_TYPE__TYPE = ATTRIBUTE_BASE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Simple Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_TYPE_FEATURE_COUNT = ATTRIBUTE_BASE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ObjectTypeImpl <em>Object Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ObjectTypeImpl
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getObjectType()
   * @generated
   */
  int OBJECT_TYPE = 13;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_TYPE__TYPE = ATTRIBUTE_BASE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Object Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_TYPE_FEATURE_COUNT = ATTRIBUTE_BASE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.InternalType <em>Internal Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.InternalType
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getInternalType()
   * @generated
   */
  int INTERNAL_TYPE = 14;


  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.PackageDeclaration <em>Package Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Declaration</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.PackageDeclaration
   * @generated
   */
  EClass getPackageDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.PackageDeclaration#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.PackageDeclaration#getElements()
   * @see #getPackageDeclaration()
   * @generated
   */
  EReference getPackageDeclaration_Elements();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine <em>State Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State Machine</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine
   * @generated
   */
  EClass getStateMachine();

  /**
   * Returns the meta object for the reference '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine#getInitialState <em>Initial State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Initial State</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine#getInitialState()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_InitialState();

  /**
   * Returns the meta object for the containment reference '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine#getControlObject <em>Control Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Control Object</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine#getControlObject()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_ControlObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine#getEvents()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_Events();

  /**
   * Returns the meta object for the containment reference list '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.StateMachine#getStates()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_States();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Base <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Base
   * @generated
   */
  EClass getBase();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Base#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Base#getName()
   * @see #getBase()
   * @generated
   */
  EAttribute getBase_Name();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.State#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.State#getTransitions()
   * @see #getState()
   * @generated
   */
  EReference getState_Transitions();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getName()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Name();

  /**
   * Returns the meta object for the reference '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getTarget()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Target();

  /**
   * Returns the meta object for the reference '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Trigger</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getTrigger()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Trigger();

  /**
   * Returns the meta object for the containment reference '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guard</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getGuard()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Guard();

  /**
   * Returns the meta object for the containment reference '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Transition#getAction()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Action();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Guard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Guard</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Guard
   * @generated
   */
  EClass getGuard();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Guard#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Guard#getName()
   * @see #getGuard()
   * @generated
   */
  EAttribute getGuard_Name();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObject <em>Control Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Control Object</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObject
   * @generated
   */
  EClass getControlObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObject#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObject#getAttributes()
   * @see #getControlObject()
   * @generated
   */
  EReference getControlObject_Attributes();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute <em>Control Object Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Control Object Attribute</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute
   * @generated
   */
  EClass getControlObjectAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute#getName()
   * @see #getControlObjectAttribute()
   * @generated
   */
  EAttribute getControlObjectAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.ControlObjectAttribute#getType()
   * @see #getControlObjectAttribute()
   * @generated
   */
  EReference getControlObjectAttribute_Type();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.AttributeBase <em>Attribute Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Base</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.AttributeBase
   * @generated
   */
  EClass getAttributeBase();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.SimpleType <em>Simple Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Type</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.SimpleType
   * @generated
   */
  EClass getSimpleType();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.SimpleType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.SimpleType#getType()
   * @see #getSimpleType()
   * @generated
   */
  EAttribute getSimpleType_Type();

  /**
   * Returns the meta object for class '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ObjectType <em>Object Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Type</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.ObjectType
   * @generated
   */
  EClass getObjectType();

  /**
   * Returns the meta object for the attribute '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.ObjectType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.ObjectType#getType()
   * @see #getObjectType()
   * @generated
   */
  EAttribute getObjectType_Type();

  /**
   * Returns the meta object for enum '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.InternalType <em>Internal Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Internal Type</em>'.
   * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.InternalType
   * @generated
   */
  EEnum getInternalType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  StateMachineDslFactory getStateMachineDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ModelImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.PackageDeclarationImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getPackageDeclaration()
     * @generated
     */
    EClass PACKAGE_DECLARATION = eINSTANCE.getPackageDeclaration();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DECLARATION__ELEMENTS = eINSTANCE.getPackageDeclaration_Elements();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineImpl <em>State Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getStateMachine()
     * @generated
     */
    EClass STATE_MACHINE = eINSTANCE.getStateMachine();

    /**
     * The meta object literal for the '<em><b>Initial State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__INITIAL_STATE = eINSTANCE.getStateMachine_InitialState();

    /**
     * The meta object literal for the '<em><b>Control Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__CONTROL_OBJECT = eINSTANCE.getStateMachine_ControlObject();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__EVENTS = eINSTANCE.getStateMachine_Events();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__STATES = eINSTANCE.getStateMachine_States();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.BaseImpl <em>Base</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.BaseImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getBase()
     * @generated
     */
    EClass BASE = eINSTANCE.getBase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASE__NAME = eINSTANCE.getBase_Name();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__TRANSITIONS = eINSTANCE.getState_Transitions();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.TransitionImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__NAME = eINSTANCE.getTransition_Name();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TARGET = eINSTANCE.getTransition_Target();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TRIGGER = eINSTANCE.getTransition_Trigger();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__GUARD = eINSTANCE.getTransition_Guard();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__ACTION = eINSTANCE.getTransition_Action();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.EventImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.GuardImpl <em>Guard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.GuardImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getGuard()
     * @generated
     */
    EClass GUARD = eINSTANCE.getGuard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUARD__NAME = eINSTANCE.getGuard_Name();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ActionImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ControlObjectImpl <em>Control Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ControlObjectImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getControlObject()
     * @generated
     */
    EClass CONTROL_OBJECT = eINSTANCE.getControlObject();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROL_OBJECT__ATTRIBUTES = eINSTANCE.getControlObject_Attributes();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ControlObjectAttributeImpl <em>Control Object Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ControlObjectAttributeImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getControlObjectAttribute()
     * @generated
     */
    EClass CONTROL_OBJECT_ATTRIBUTE = eINSTANCE.getControlObjectAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL_OBJECT_ATTRIBUTE__NAME = eINSTANCE.getControlObjectAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROL_OBJECT_ATTRIBUTE__TYPE = eINSTANCE.getControlObjectAttribute_Type();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.AttributeBaseImpl <em>Attribute Base</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.AttributeBaseImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getAttributeBase()
     * @generated
     */
    EClass ATTRIBUTE_BASE = eINSTANCE.getAttributeBase();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.SimpleTypeImpl <em>Simple Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.SimpleTypeImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getSimpleType()
     * @generated
     */
    EClass SIMPLE_TYPE = eINSTANCE.getSimpleType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_TYPE__TYPE = eINSTANCE.getSimpleType_Type();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ObjectTypeImpl <em>Object Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.ObjectTypeImpl
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getObjectType()
     * @generated
     */
    EClass OBJECT_TYPE = eINSTANCE.getObjectType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_TYPE__TYPE = eINSTANCE.getObjectType_Type();

    /**
     * The meta object literal for the '{@link org.salgar.swf_statemachine.xtext.stateMachineDsl.InternalType <em>Internal Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.InternalType
     * @see org.salgar.swf_statemachine.xtext.stateMachineDsl.impl.StateMachineDslPackageImpl#getInternalType()
     * @generated
     */
    EEnum INTERNAL_TYPE = eINSTANCE.getInternalType();

  }

} //StateMachineDslPackage
