/**
 * generated by Xtext 2.9.1
 */
package org.salgar.swf_statemachine.xtext.validation;

import org.salgar.swf_statemachine.xtext.validation.AbstractStateMachineDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StateMachineDslValidator extends AbstractStateMachineDslValidator {
}
